# Generated by Django 2.2.12 on 2020-06-12 18:17

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='avatar.png', upload_to='user_avatar/', verbose_name='头像'),
        ),
    ]
