# Generated by Django 2.2.12 on 2020-06-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='已阅读新手教程'),
        ),
        migrations.AddField(
            model_name='user',
            name='levelname',
            field=models.CharField(default='新手', max_length=128, verbose_name='称号'),
        ),
    ]
