# Generated by Django 2.2.12 on 2020-06-12 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='absoluteUps',
            field=models.IntegerField(default=0),
        ),
    ]
