# Generated by Django 2.2.12 on 2020-06-13 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-last_edit',)},
        ),
    ]
