# Generated by Django 2.2.12 on 2020-06-12 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upanddown',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.Comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='section',
            field=models.CharField(choices=[(0, '讨论区'), (1, '刷题区'), (2, '校园区'), (3, '课程推荐区'), (4, '资源区')], default='讨论区', max_length=32, verbose_name='板块'),
        ),
        migrations.AlterField(
            model_name='upanddown',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.Post'),
        ),
        migrations.AlterUniqueTogether(
            name='upanddown',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.RemoveField(
            model_name='upanddown',
            name='is_up',
        ),
    ]
