# Generated by Django 2.2.12 on 2020-06-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20200613_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=64, verbose_name='帖子标题'),
        ),
    ]
