# Generated by Django 2.2.12 on 2020-06-08 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_comment_reply_to_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_top',
            field=models.BooleanField(default=False),
        ),
    ]
