# Generated by Django 2.2.12 on 2020-06-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):


    operations = [
        migrations.AlterField(
            model_name='post',
            name='section',
            field=models.CharField(choices=[(0, '讨论区'), (1, '刷题区'), (2, '校园区'), (3, '课程推荐区'), (4, '资源区')], default='讨论区', max_length=32, verbose_name='板块'),
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
