# Generated by Django 2.2.12 on 2020-06-14 01:41

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20200614_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=204800),
        ),
        migrations.AlterField(
            model_name='post',
            name='level_restriction',
            field=models.CharField(choices=[('1', '不设限制'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='1', max_length=32, verbose_name='等级限制'),
        ),
        migrations.AlterField(
            model_name='post',
            name='section',
            field=models.CharField(choices=[('1', '讨论区'), ('2', '课程推荐'), ('3', '刷题'), ('4', '校园周边'), ('5', '资源共享')], default='讨论区', max_length=32, verbose_name='板块'),
        ),
    ]
