# Generated by Django 2.2.12 on 2020-06-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_remove_post_absoluteups'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='absoluteUps',
            field=models.IntegerField(default=0),
        ),
    ]
