# Generated by Django 2.2.12 on 2020-06-09 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_post_is_top'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply_to_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replyToComment', to='forum.Comment'),
        ),
    ]
