# Generated by Django 2.2.12 on 2020-06-09 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20200609_0005'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Section',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='section',
        ),
    ]
