# Generated by Django 2.2.12 on 2020-06-13 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20200613_1332'),
        ('forum', '0006_auto_20200613_1105'),
    ]

    operations = [
    ]
