# Generated by Django 2.2.12 on 2020-06-13 17:36

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_merge_20200613_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=204800),
        ),
        migrations.AlterField(
            model_name='post',
            name='section',
            field=models.CharField(choices=[('1', '讨论区'), ('2', '课程推荐'), ('3', '刷题'), ('4', '校园周边'), ('5', '资源共享')], default='讨论区', max_length=32, verbose_name='板块'),
        ),
    ]
