# Generated by Django 2.2.5 on 2020-06-03 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20200602_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_changed',
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(null=True, upload_to='img', verbose_name='图片'),
        ),
    ]
