# Generated by Django 2.2.5 on 2020-06-02 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_auto_20200529_1537'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoritepost',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='favoritepost',
            name='PostID',
        ),
        migrations.RemoveField(
            model_name='favoritepost',
            name='UserID',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='follow',
            name='FollowedID',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='FollowerID',
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='message',
            name='ReceiverID',
        ),
        migrations.RemoveField(
            model_name='message',
            name='SenderID',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='UserID',
        ),
        migrations.RemoveField(
            model_name='userspace',
            name='UserID',
        ),
        migrations.DeleteModel(
            name='BlackList',
        ),
        migrations.DeleteModel(
            name='FavoritePost',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='UserSpace',
        ),
    ]
