# Generated by Django 2.2.12 on 2020-06-11 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blacklist',
            options={'ordering': ['-BlockTime']},
        ),
        migrations.AlterModelOptions(
            name='favoritepost',
            options={'ordering': ['-FavoriteTime']},
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ['-FollowTime']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-SendTime']},
        ),
    ]
